server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:h2:file:~/data/loans-service
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    properties.hibernate.format_sql: true
  h2:
    console.enabled: true
  sql:
    init:
      mode: always