name: jira update

on: 
 push:
   branches: [main]
#  pull_request:
#    types: [closed]
#    branches: [main]
#       - main
#       - 'releases/**'

jobs:
  build:
    name: Jira actions
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v3
      - name: Login on Jira
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
                    
      - name: Find Jira issue key in commit messages
        id: jira-key
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: commits
     
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v19
        
      - name: Get LenderService changes
        id: changed-lender-service
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/LenderService.java
          files_ignore: |
            *.yml
            *.xml
            *.sql
                    
      - name: Add Jira label when LenderService file changes
        if: steps.changed-lender-service.outputs.any_modified == 'true'
        run: |
          curl -D- -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} -X PUT --data '{ "update": { "labels": [{"add":"NewLabel"}]}}' -H "Content-Type: application/json" '${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${{ steps.jira-key.outputs.issue }}'
          
      - name: Get changelog file creation
        id: added-changelog-file
        uses: tj-actions/changed-files@v19
        with:
          files: |
            **/changelog.xml
          files_ignore: |
            *.yml
            *.java
            *.sql

      - name: Set custon field value when changelog.xml are added
        if: steps.added-changelog-file.outputs.any_changed == 'true'
        run: |
          curl -D- -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} -X PUT --data '{ "fields" : { "customfield_10029" : "${{ steps.added-changelog-file.outputs.added_files }}"}}' -H "Content-Type: application/json" '${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/${{ steps.jira-key.outputs.issue }}'
