name: build
on: 
 push: 
  branches:
      - main
      - 'releases/**'
 pull_request:
  branches:
      - main
      - 'releases/**'

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      
      - name: Build
        run: mvn clean package
      
      - name: Run Tests
        run: mvn test
